const revolutionMercury = (counter) => {
    switch (counter) {
        case 0:
            document.getElementById('h7').style.display = "block";
            document.getElementById('h6').style.display = "none";
            document.getElementById('g6').style.display = "none";
            document.getElementById('f6').style.display = "none";
            document.getElementById('f7').style.display = "none";
            document.getElementById('f8').style.display = "none";
            document.getElementById('g8').style.display = "none";
            document.getElementById('h8').style.display = "none";
            break;
        case 1:
            document.getElementById('h7').style.display = "none";
            document.getElementById('h6').style.display = "block";
            document.getElementById('g6').style.display = "none";
            document.getElementById('f6').style.display = "none";
            document.getElementById('f7').style.display = "none";
            document.getElementById('f8').style.display = "none";
            document.getElementById('g8').style.display = "none";
            document.getElementById('h8').style.display = "none";
            break;
        case 2:
            document.getElementById('h7').style.display = "none";
            document.getElementById('h6').style.display = "none";
            document.getElementById('g6').style.display = "block";
            document.getElementById('f6').style.display = "none";
            document.getElementById('f7').style.display = "none";
            document.getElementById('f8').style.display = "none";
            document.getElementById('g8').style.display = "none";
            document.getElementById('h8').style.display = "none";
            break;
        case 3:
            document.getElementById('h7').style.display = "none";
            document.getElementById('h6').style.display = "none";
            document.getElementById('g6').style.display = "none";
            document.getElementById('f6').style.display = "block";
            document.getElementById('f7').style.display = "none";
            document.getElementById('f8').style.display = "none";
            document.getElementById('g8').style.display = "none";
            document.getElementById('h8').style.display = "none";
            break;
        case 4:
            document.getElementById('h7').style.display = "none";
            document.getElementById('h6').style.display = "none";
            document.getElementById('g6').style.display = "none";
            document.getElementById('f6').style.display = "none";
            document.getElementById('f7').style.display = "block";
            document.getElementById('f8').style.display = "none";
            document.getElementById('g8').style.display = "none";
            document.getElementById('h8').style.display = "none";
            break;
        case 5:
            document.getElementById('h7').style.display = "none";
            document.getElementById('h6').style.display = "none";
            document.getElementById('g6').style.display = "none";
            document.getElementById('f6').style.display = "none";
            document.getElementById('f7').style.display = "none";
            document.getElementById('f8').style.display = "block";
            document.getElementById('g8').style.display = "none";
            document.getElementById('h8').style.display = "none";
            break;
        case 6:
            document.getElementById('h7').style.display = "none";
            document.getElementById('h6').style.display = "none";
            document.getElementById('g6').style.display = "none";
            document.getElementById('f6').style.display = "none";
            document.getElementById('f7').style.display = "none";
            document.getElementById('f8').style.display = "none";
            document.getElementById('g8').style.display = "block";
            document.getElementById('h8').style.display = "none";
            break;
        case 7:
            document.getElementById('h7').style.display = "none";
            document.getElementById('h6').style.display = "none";
            document.getElementById('g6').style.display = "none";
            document.getElementById('f6').style.display = "none";
            document.getElementById('f7').style.display = "none";
            document.getElementById('f8').style.display = "none";
            document.getElementById('g8').style.display = "none";
            document.getElementById('h8').style.display = "block";
            break;
    }
};

const revolutionVenus = (counter) => {
    switch (counter) {
        case 0:
            document.getElementById('i7').style.display = "block";
            document.getElementById('i6').style.display = "none";
            document.getElementById('i5').style.display = "none";
            document.getElementById('h5').style.display = "none";
            document.getElementById('g5').style.display = "none";
            document.getElementById('f5').style.display = "none";
            document.getElementById('e5').style.display = "none";
            document.getElementById('e6').style.display = "none";
            document.getElementById('e7').style.display = "none";
            document.getElementById('e8').style.display = "none";
            document.getElementById('e9').style.display = "none";
            document.getElementById('f9').style.display = "none";
            document.getElementById('g9').style.display = "none";
            document.getElementById('h9').style.display = "none";
            document.getElementById('i9').style.display = "none";
            document.getElementById('i8').style.display = "none";
            break;
        case 1:
            document.getElementById('i7').style.display = "none";
            document.getElementById('i6').style.display = "block";
            document.getElementById('i5').style.display = "none";
            document.getElementById('h5').style.display = "none";
            document.getElementById('g5').style.display = "none";
            document.getElementById('f5').style.display = "none";
            document.getElementById('e5').style.display = "none";
            document.getElementById('e6').style.display = "none";
            document.getElementById('e7').style.display = "none";
            document.getElementById('e8').style.display = "none";
            document.getElementById('e9').style.display = "none";
            document.getElementById('f9').style.display = "none";
            document.getElementById('g9').style.display = "none";
            document.getElementById('h9').style.display = "none";
            document.getElementById('i9').style.display = "none";
            document.getElementById('i8').style.display = "none";
            break;
        case 2:
            document.getElementById('i7').style.display = "none";
            document.getElementById('i6').style.display = "none";
            document.getElementById('i5').style.display = "block";
            document.getElementById('h5').style.display = "none";
            document.getElementById('g5').style.display = "none";
            document.getElementById('f5').style.display = "none";
            document.getElementById('e5').style.display = "none";
            document.getElementById('e6').style.display = "none";
            document.getElementById('e7').style.display = "none";
            document.getElementById('e8').style.display = "none";
            document.getElementById('e9').style.display = "none";
            document.getElementById('f9').style.display = "none";
            document.getElementById('g9').style.display = "none";
            document.getElementById('h9').style.display = "none";
            document.getElementById('i9').style.display = "none";
            document.getElementById('i8').style.display = "none";
            break;
        case 3:
            document.getElementById('i7').style.display = "none";
            document.getElementById('i6').style.display = "none";
            document.getElementById('i5').style.display = "none";
            document.getElementById('h5').style.display = "block";
            document.getElementById('g5').style.display = "none";
            document.getElementById('f5').style.display = "none";
            document.getElementById('e5').style.display = "none";
            document.getElementById('e6').style.display = "none";
            document.getElementById('e7').style.display = "none";
            document.getElementById('e8').style.display = "none";
            document.getElementById('e9').style.display = "none";
            document.getElementById('f9').style.display = "none";
            document.getElementById('g9').style.display = "none";
            document.getElementById('h9').style.display = "none";
            document.getElementById('i9').style.display = "none";
            document.getElementById('i8').style.display = "none";
            break;
        case 4:
            document.getElementById('i7').style.display = "none";
            document.getElementById('i6').style.display = "none";
            document.getElementById('i5').style.display = "none";
            document.getElementById('h5').style.display = "none";
            document.getElementById('g5').style.display = "block";
            document.getElementById('f5').style.display = "none";
            document.getElementById('e5').style.display = "none";
            document.getElementById('e6').style.display = "none";
            document.getElementById('e7').style.display = "none";
            document.getElementById('e8').style.display = "none";
            document.getElementById('e9').style.display = "none";
            document.getElementById('f9').style.display = "none";
            document.getElementById('g9').style.display = "none";
            document.getElementById('h9').style.display = "none";
            document.getElementById('i9').style.display = "none";
            document.getElementById('i8').style.display = "none";
            break;
        case 5:
            document.getElementById('i7').style.display = "none";
            document.getElementById('i6').style.display = "none";
            document.getElementById('i5').style.display = "none";
            document.getElementById('h5').style.display = "none";
            document.getElementById('g5').style.display = "none";
            document.getElementById('f5').style.display = "block";
            document.getElementById('e5').style.display = "none";
            document.getElementById('e6').style.display = "none";
            document.getElementById('e7').style.display = "none";
            document.getElementById('e8').style.display = "none";
            document.getElementById('e9').style.display = "none";
            document.getElementById('f9').style.display = "none";
            document.getElementById('g9').style.display = "none";
            document.getElementById('h9').style.display = "none";
            document.getElementById('i9').style.display = "none";
            document.getElementById('i8').style.display = "none";
            break;
        case 6:
            document.getElementById('i7').style.display = "none";
            document.getElementById('i6').style.display = "none";
            document.getElementById('i5').style.display = "none";
            document.getElementById('h5').style.display = "none";
            document.getElementById('g5').style.display = "none";
            document.getElementById('f5').style.display = "none";
            document.getElementById('e5').style.display = "block";
            document.getElementById('e6').style.display = "none";
            document.getElementById('e7').style.display = "none";
            document.getElementById('e8').style.display = "none";
            document.getElementById('e9').style.display = "none";
            document.getElementById('f9').style.display = "none";
            document.getElementById('g9').style.display = "none";
            document.getElementById('h9').style.display = "none";
            document.getElementById('i9').style.display = "none";
            document.getElementById('i8').style.display = "none";
            break;
        case 7:
            document.getElementById('i7').style.display = "none";
            document.getElementById('i6').style.display = "none";
            document.getElementById('i5').style.display = "none";
            document.getElementById('h5').style.display = "none";
            document.getElementById('g5').style.display = "none";
            document.getElementById('f5').style.display = "none";
            document.getElementById('e5').style.display = "none";
            document.getElementById('e6').style.display = "block";
            document.getElementById('e7').style.display = "none";
            document.getElementById('e8').style.display = "none";
            document.getElementById('e9').style.display = "none";
            document.getElementById('f9').style.display = "none";
            document.getElementById('g9').style.display = "none";
            document.getElementById('h9').style.display = "none";
            document.getElementById('i9').style.display = "none";
            document.getElementById('i8').style.display = "none";
            break;
        case 8:
            document.getElementById('i7').style.display = "none";
            document.getElementById('i6').style.display = "none";
            document.getElementById('i5').style.display = "none";
            document.getElementById('h5').style.display = "none";
            document.getElementById('g5').style.display = "none";
            document.getElementById('f5').style.display = "none";
            document.getElementById('e5').style.display = "none";
            document.getElementById('e6').style.display = "none";
            document.getElementById('e7').style.display = "block";
            document.getElementById('e8').style.display = "none";
            document.getElementById('e9').style.display = "none";
            document.getElementById('f9').style.display = "none";
            document.getElementById('g9').style.display = "none";
            document.getElementById('h9').style.display = "none";
            document.getElementById('i9').style.display = "none";
            document.getElementById('i8').style.display = "none";
            break;
        case 9:
            document.getElementById('i7').style.display = "none";
            document.getElementById('i6').style.display = "none";
            document.getElementById('i5').style.display = "none";
            document.getElementById('h5').style.display = "none";
            document.getElementById('g5').style.display = "none";
            document.getElementById('f5').style.display = "none";
            document.getElementById('e5').style.display = "none";
            document.getElementById('e6').style.display = "none";
            document.getElementById('e7').style.display = "none";
            document.getElementById('e8').style.display = "block";
            document.getElementById('e9').style.display = "none";
            document.getElementById('f9').style.display = "none";
            document.getElementById('g9').style.display = "none";
            document.getElementById('h9').style.display = "none";
            document.getElementById('i9').style.display = "none";
            document.getElementById('i8').style.display = "none";
            break;
        case 10:
            document.getElementById('i7').style.display = "none";
            document.getElementById('i6').style.display = "none";
            document.getElementById('i5').style.display = "none";
            document.getElementById('h5').style.display = "none";
            document.getElementById('g5').style.display = "none";
            document.getElementById('f5').style.display = "none";
            document.getElementById('e5').style.display = "none";
            document.getElementById('e6').style.display = "none";
            document.getElementById('e7').style.display = "none";
            document.getElementById('e8').style.display = "none";
            document.getElementById('e9').style.display = "block";
            document.getElementById('f9').style.display = "none";
            document.getElementById('g9').style.display = "none";
            document.getElementById('h9').style.display = "none";
            document.getElementById('i9').style.display = "none";
            document.getElementById('i8').style.display = "none";
            break;
        case 11:
            document.getElementById('i7').style.display = "none";
            document.getElementById('i6').style.display = "none";
            document.getElementById('i5').style.display = "none";
            document.getElementById('h5').style.display = "none";
            document.getElementById('g5').style.display = "none";
            document.getElementById('f5').style.display = "none";
            document.getElementById('e5').style.display = "none";
            document.getElementById('e6').style.display = "none";
            document.getElementById('e7').style.display = "none";
            document.getElementById('e8').style.display = "none";
            document.getElementById('e9').style.display = "none";
            document.getElementById('f9').style.display = "block";
            document.getElementById('g9').style.display = "none";
            document.getElementById('h9').style.display = "none";
            document.getElementById('i9').style.display = "none";
            document.getElementById('i8').style.display = "none";
            break;
        case 12:
            document.getElementById('i7').style.display = "none";
            document.getElementById('i6').style.display = "none";
            document.getElementById('i5').style.display = "none";
            document.getElementById('h5').style.display = "none";
            document.getElementById('g5').style.display = "none";
            document.getElementById('f5').style.display = "none";
            document.getElementById('e5').style.display = "none";
            document.getElementById('e6').style.display = "none";
            document.getElementById('e7').style.display = "none";
            document.getElementById('e8').style.display = "none";
            document.getElementById('e9').style.display = "none";
            document.getElementById('f9').style.display = "none";
            document.getElementById('g9').style.display = "block";
            document.getElementById('h9').style.display = "none";
            document.getElementById('i9').style.display = "none";
            document.getElementById('i8').style.display = "none";
            break;
        case 13:
            document.getElementById('i7').style.display = "none";
            document.getElementById('i6').style.display = "none";
            document.getElementById('i5').style.display = "none";
            document.getElementById('h5').style.display = "none";
            document.getElementById('g5').style.display = "none";
            document.getElementById('f5').style.display = "none";
            document.getElementById('e5').style.display = "none";
            document.getElementById('e6').style.display = "none";
            document.getElementById('e7').style.display = "none";
            document.getElementById('e8').style.display = "none";
            document.getElementById('e9').style.display = "none";
            document.getElementById('f9').style.display = "none";
            document.getElementById('g9').style.display = "none";
            document.getElementById('h9').style.display = "block";
            document.getElementById('i9').style.display = "none";
            document.getElementById('i8').style.display = "none";
            break;
        case 14:
            document.getElementById('i7').style.display = "none";
            document.getElementById('i6').style.display = "none";
            document.getElementById('i5').style.display = "none";
            document.getElementById('h5').style.display = "none";
            document.getElementById('g5').style.display = "none";
            document.getElementById('f5').style.display = "none";
            document.getElementById('e5').style.display = "none";
            document.getElementById('e6').style.display = "none";
            document.getElementById('e7').style.display = "none";
            document.getElementById('e8').style.display = "none";
            document.getElementById('e9').style.display = "none";
            document.getElementById('f9').style.display = "none";
            document.getElementById('g9').style.display = "none";
            document.getElementById('h9').style.display = "none";
            document.getElementById('i9').style.display = "block";
            document.getElementById('i8').style.display = "none";
            break;
        case 15:
            document.getElementById('i7').style.display = "none";
            document.getElementById('i6').style.display = "none";
            document.getElementById('i5').style.display = "none";
            document.getElementById('h5').style.display = "none";
            document.getElementById('g5').style.display = "none";
            document.getElementById('f5').style.display = "none";
            document.getElementById('e5').style.display = "none";
            document.getElementById('e6').style.display = "none";
            document.getElementById('e7').style.display = "none";
            document.getElementById('e8').style.display = "none";
            document.getElementById('e9').style.display = "none";
            document.getElementById('f9').style.display = "none";
            document.getElementById('g9').style.display = "none";
            document.getElementById('h9').style.display = "none";
            document.getElementById('i9').style.display = "none";
            document.getElementById('i8').style.display = "block";
            break;
    }
};

const myCallback = () => {
    let date = new Date();
    let counter = date.getSeconds();
    console.log(counter);
    revolutionMercury(counter % 8);
    revolutionVenus(counter % 16);
    console.log(date.toLocaleTimeString());
};

const intervalID = setInterval(myCallback, 1000);